-- liquibase formatted sql

-- changeset out-gerasimov-kv:1604405505632-1
CREATE TABLE product (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount BIGINT, price BIGINT, product_type VARCHAR(255), text VARCHAR(255), CONSTRAINT product_pkey PRIMARY KEY (id));

-- changeset out-gerasimov-kv:1604405505632-2
CREATE TABLE user_cart_cart (user_cart_id BIGINT NOT NULL, cart_id BIGINT NOT NULL);

-- changeset out-gerasimov-kv:1604405505632-3
CREATE TABLE user_cart (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(255), CONSTRAINT user_cart_pkey PRIMARY KEY (id));

-- changeset out-gerasimov-kv:1604405505632-4
CREATE TABLE user_role (user_id BIGINT NOT NULL, roles VARCHAR(255));

-- changeset out-gerasimov-kv:1604405505632-5
CREATE TABLE usr (id BIGINT NOT NULL, active BOOLEAN NOT NULL, email VARCHAR(255), password VARCHAR(255), username VARCHAR(255), CONSTRAINT usr_pkey PRIMARY KEY (id));

-- changeset out-gerasimov-kv:1604405505632-6
ALTER TABLE user_cart_cart ADD CONSTRAINT fk22xq633o7ox2vx8b8r38fcm8w FOREIGN KEY (cart_id) REFERENCES product (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset out-gerasimov-kv:1604405505632-7
ALTER TABLE user_cart_cart ADD CONSTRAINT fk9b2y9a5six60e1j0fjly589dl FOREIGN KEY (user_cart_id) REFERENCES user_cart (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset out-gerasimov-kv:1604405505632-8
ALTER TABLE user_role ADD CONSTRAINT fkfpm8swft53ulq2hl11yplpr5 FOREIGN KEY (user_id) REFERENCES usr (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset out-gerasimov-kv:1604405505632-9
CREATE SEQUENCE  IF NOT EXISTS hibernate_sequence AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

