-- liquibase formatted sql

-- changeset out-gerasimov-kv:1604405505632-1
CREATE TABLE product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    amount BIGINT,
    price BIGINT,
    product_type VARCHAR(255),
    text VARCHAR(255),
    CONSTRAINT product_pkey PRIMARY KEY (id)
);
-- rollback DROP TABLE product;

-- changeset out-gerasimov-kv:1604405505632-2
CREATE TABLE user_cart_cart (
    user_cart_id BIGINT NOT NULL,
    cart_id BIGINT NOT NULL
);
-- rollback DROP TABLE user_cart_cart;

-- changeset out-gerasimov-kv:1604405505632-3
CREATE TABLE user_cart (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255),
    CONSTRAINT user_cart_pkey PRIMARY KEY (id)
);
-- rollback DROP TABLE user_cart;

-- changeset out-gerasimov-kv:1604405505632-4
CREATE TABLE user_role (
    user_id BIGINT NOT NULL,
    roles VARCHAR(255)
);
-- rollback DROP TABLE user_role;

-- changeset out-gerasimov-kv:1604405505632-5
CREATE TABLE usr (
    id BIGINT NOT NULL,
    active BOOLEAN NOT NULL,
    email VARCHAR(255),
    password VARCHAR(255),
    username VARCHAR(255),
    CONSTRAINT usr_pkey PRIMARY KEY (id)
);
-- rollback DROP TABLE usr;

-- changeset out-gerasimov-kv:1604405505632-6
ALTER TABLE user_cart_cart
    ADD CONSTRAINT fk_ucc_product FOREIGN KEY (cart_id) REFERENCES product (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
-- rollback ALTER TABLE user_cart_cart DROP FOREIGN KEY (cart_id);

-- changeset out-gerasimov-kv:1604405505632-7
ALTER TABLE user_cart_cart
    ADD CONSTRAINT fk_ucc_user_cart FOREIGN KEY (user_cart_id) REFERENCES user_cart (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
-- rollback ALTER TABLE user_cart_cart DROP FOREIGN KEY (user_cart_id);

-- changeset out-gerasimov-kv:1604405505632-8
ALTER TABLE user_role
    ADD CONSTRAINT fk_user_role_usr FOREIGN KEY (user_id) REFERENCES usr (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
-- rollback ALTER TABLE user_cart_cart DROP FOREIGN KEY (user_id);

-- changeset out-gerasimov-kv:1604405505632-9
CREATE SEQUENCE IF NOT EXISTS hibernate_sequence AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;
-- rollback DROP SEQUENCE IF EXISTS hibernate_sequence RESTRICT;